### ISSUE TITLE
Issue with structure of criterion #58

### ISSUE THREAD

**Issue by lotzmann** [OP-TED/ESPD-EDM#203]
There is an issue with the two data elements within the ONFALSE subgroup of criterion 58: The DESCRIPTION (marked (2) in the screenshot) is a mandatory element that always must be provided, no matter what the state of INDICATOR (1) is. Thereby, the text associated with the description ("If the relevant documentation is available electronically, please indicate:") does not make clear what needs to indicated, nor does it justify to be mandatory.

It might make sense to allow some kind of description or explanation related to the indicator independent of the state, but at least for the case that (1) was answered with no/false, this description must not be mandatory.

Please check if this criterion could be improved in this respect. What I also find a bit problematic is that several aspects (provision of certificate, direct access by CA, free of charge) are enquired in just this one indicator.

![issue](https://user-images.githubusercontent.com/20660160/49087306-ec473900-f256-11e8-999b-b2e984b72364.png)

**Comment by paulakeen** [comment]
Dear Ulf, 

I think you're absolutely right. For me what is weird is that this is a question. Instead i would see it as a "Caption" requesting the EO to use the block about evidences to supply relevant documentation if it is available electronically. 

With MC and ESPDint the discussion about whether URL pointing at evidences make sense or not in an ESPD Regulated. The answer by MC was: "YES" it does make sense, because it's just to show that the EO is saying the truth and, later on, at awarding time the CA has the possibility of getting the evidence.

Would this work for you? -->


![usetheblock](https://user-images.githubusercontent.com/16134316/49291974-3b39dc00-f4ac-11e8-95c4-27577301c75b.png)

**Comment by paulakeen** [comment]
IF YOU DO NOT AGREE TO THIS SOLUTION PLEASE REACT ASAP.

**Comment by jerouris** [comment]
Enric, we have agreed not to show captions in the UI, because these where added to circumvent the cardinality issues with UBL. According to this solution, should we show the CAPTION now, or should it be remain hidden?

**Comment by paulakeen** [comment]
I don’t like using captions either, but the alternative would be having a REQUIREMENT inside a QUESTION, which is even worse and I DO NOT WANT TO DO THAT!!!! ….the easiest way to solve this would be removing this line, but this for MC to confirm if we can do it. I’ll call him.

**Comment by paulakeen** [comment]
We have decided, jointly with MC and Jerry, to remove this line. If you check this part with the Regulation (page 10) you will see that this refers to the possibility of providing an evidence. For this, the block "Is this information available electronically?" (QUESTION_GROUP uuid "7458d42a-e581-4640-9283-34ceb3ad4345") should be used.

![c58](https://user-images.githubusercontent.com/16134316/49294861-750ee080-f4b4-11e8-9627-88c95b23b301.png)

**Comment by lotzmann** [comment]
Agree, looks like a good solution to me.

**Comment by sakispantazis** [comment]
It seems there is still an issue with the structure regarding criterion 58 (i.e. the question asking if the EO is registered on an official list of approved economic operators or has an equivalent certificate from a pre-qualification system), leading to a faulty functionality and consequently incorrect content in the produced ESPD requests/responses. My guess is that the issue has occurred because the text of the ESPD EU Regulation (7/2016) does not use indentation in order to  “visualize” any nested conditional statements, which led to a misinterpretation of the stipulations regarding this criterion.

The current implementation of the structure is considering that the conditions  “If yes:” and “If no:” belong to the same conditional (“if-then-else”) statement, which is not true, i.e. question (e) should always appear along with (a), (b), (c) and (d)!
I talked this through with our Ministry’s legal department as well as with the Hellenic Single Public Procurement Authority, and the interpretation of the Regulation in this case should be:

![image](https://user-images.githubusercontent.com/16813866/55734052-92862500-5a27-11e9-8b1c-c6ebd9ec307b.png)

**Comment by ec-mcs** [comment]
You are right. We interpret the logic in the wrong way. Besides that, this section creates some confusion for the users. In the light of OOP a pre-qualification service should answer the criteria individually instead of using this section. As well this criteria is simply a “light” and less structured duplication of Part III and Part IV. We need to discuss how to proceed, because a change here would affect all ESPD services.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM

**Comment by sakispantazis** [comment]
Dear @jerouris,
we are using v.2.1.0 in our implementation, but we still have this issue. Any thoughts?

**Comment by rantati7** [comment]
#58 I do not know if you have found a solution to this one - hence I ask this anyhow. 

Why is the question asked in this place at all? The question:  "Will the economic operator be able to provide a certificate with regard to the payment of social security contributions and taxes or provide information enabling  the contracting authority or contracting entity to obtaining it directly by accessing a national database in any Member State that is available free of  charge?"

The same question (or question implying the same answer) is required in #7 and #8 and #7 and #8 are mandatory questions that have to asked from all suppliers... in version 1.0.2 #7 and #8 even had nearly the same text: 

"Is this information available at no cost to the authorities from an EU Member State database? Yes No"
--
Have you decided to remove this question from #58 (I thought I understood it'd be removed?)
