### ISSUE TITLE
"Special requierements check" criteria has closing tags for subgroups on the same levels in taxonomy #interproc

### ISSUE THREAD

**Issue by JustinaZaltauskaite** [OP-TED/ESPD-EDM#371]
"Special requierements check" criteria has closing tags for QUESTION_SUBGROUP on the same levels in taxonomy, although one of the group is inside the other.
At first glance looks like an indentation issue, but maybe something is missing

![image](https://user-images.githubusercontent.com/75019622/211339304-43831a4f-32b7-4e99-87f0-2370084aca10.png)

**Comment by ghost** [comment]
Good afternoon,
Thank you very much for your comment.

The reported indentation issue has been fixed in release v3.1.0.

Kind regards,
The ESPD Team

**Comment by JustinaZaltauskaite** [comment]
@delgajc  Checked if I had the newest version of taxonomy for 3.1.0 - and yes the one was from 3.1.0
So, Issue still exists
Downloaded taxonomy from https://github.com/OP-TED/ESPD-EDM/blob/master/codelists/ESPD-criterion.xlsx on 2023/01/10
![image](https://user-images.githubusercontent.com/75019622/211740647-848e30a9-14f5-465c-b381-e39f30ecbdeb.png)

**Comment by ghost** [comment]
Good afternoon,
apologies, you are right, this fix was not included in release 3.1.0. It's now fixed in the Excel file and you can find it [here.](https://github.com/OP-TED/ESPD-EDM/blob/master/codelists/ESPD-criterion.xlsx)

Kind Regards,
The ESPD Team.

**Comment by JustinaZaltauskaite** [comment]
@delgajc any ideas when all newest fixes will be released (merged into main) officially?

**Comment by ghost** [comment]
Good afternoon,
this fix will be included in the upcoming major release 4.0.0 we are working on.

Kind Regards,
The ESDP Team.
